# Generated by Django 4.1.6 on 2023-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_num_ratings_remove_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
