# Generated by Django 4.1.5 on 2023-01-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_anime_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serials',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='serials',
            name='category',
        ),
        migrations.RemoveField(
            model_name='serials',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='serials',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='Serials',
        ),
    ]
