# Generated by Django 4.1.6 on 2023-02-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_num_ratings_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='num_ratings',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
