# Generated by Django 4.1.5 on 2023-01-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movieshots_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshots',
            name='image',
            field=models.ImageField(upload_to='movie_shots/', verbose_name='Изображение'),
        ),
    ]
