# Generated by Django 4.1.6 on 2023-02-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
