# Generated by Django 4.1.6 on 2023-02-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_category',
            field=models.PositiveBigIntegerField(default=16, verbose_name='Возрастная категория'),
        ),
    ]
