# Generated by Django 4.1.6 on 2023-02-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_age_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
