# Generated by Django 4.1.6 on 2023-02-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movierating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieRating',
        ),
    ]
